// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwqczxevgabnpzjhmqvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cWN6eGV2Z2FibnB6amhtcXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODE3MzgsImV4cCI6MjA3MzE1NzczOH0.0MaOd5B38UZIEUeCzC5hUFJr2hU4uUmpZt5NQli76Uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});